# Generated by Django 5.0.3 on 2024-07-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('min_salary', models.CharField(max_length=100)),
                ('max_salary', models.CharField(max_length=100)),
            ],
        ),
    ]
