# Generated by Django 5.0.3 on 2024-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
    ]
