# Generated by Django 5.0.3 on 2024-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_jobs_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
