# Generated by Django 5.0.3 on 2024-07-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='msg',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.AddField(
            model_name='messages',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
