# Generated by Django 5.0.3 on 2024-07-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_msg_messages_message_remove_messages_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='send_date',
            field=models.DateField(auto_now=True),
        ),
    ]
