# Generated by Django 5.0.3 on 2024-09-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_messages_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
